#pragma once
#include <Arduino.h>
#include <avr/pgmspace.h>

// Generated by export_arduino_model.py; banana freshness only.
// Nine engineered inputs; int16 thresholds use per-feature Q factors.
// 0=spoiled, 1=fresh, 2=no fruit.
constexpr uint8_t FRESHNESS_INPUTS = 9;
constexpr uint8_t FRESHNESS_NODE_COUNT = 9;
constexpr int16_t kNoFruitRawMq3ThresholdQ8 = 4220;
const float kCustomToOpenGain[3] PROGMEM = {
  0.757511638f, 13.0647131f, 3.60962567f
};
const float kCustomToOpenOffset[3] PROGMEM = {
  -331.743335f, -140.018315f, -124.921123f
};
const uint16_t kFeatureQ[FRESHNESS_INPUTS] PROGMEM = {
  1024, 4096, 16, 16, 512, 16, 16, 16, 16
};

struct __attribute__((packed)) FreshnessNode {
  int16_t thresholdQ;
  uint8_t right;
  uint8_t feature; // 0..8 from FEATURES, 255=leaf
  uint8_t fresh;   // leaf class only
};
static_assert(sizeof(FreshnessNode) == 5, "Unexpected tree node size");
const FreshnessNode kFreshnessTree[FRESHNESS_NODE_COUNT] PROGMEM = {
  {10120, 8, 6, 0},
  {1992, 7, 3, 0},
  {-7816, 6, 2, 0},
  {5368, 5, 4, 0},
  {0, 0, 255, 1},
  {0, 0, 255, 0},
  {0, 0, 255, 1},
  {0, 0, 255, 0},
  {0, 0, 255, 0},
};
