"""Train and export the quantized banana freshness tree for Arduino Uno."""

from pathlib import Path

import numpy as np
from sklearn.metrics import balanced_accuracy_score, f1_score, recall_score
from sklearn.model_selection import GroupShuffleSplit

from freshness_tree_model import (
    FEATURES, FEATURE_Q, GATE_Q, calibration, even_sample, load_open_resampled,
    load_recording, make_features, make_model, map_custom, model_flash_bytes,
    open_block_groups,
    open_training_data,
    predict_quantized, quantize_model,
)

OUTPUT = Path(__file__).resolve().parent / 'arduino_sketches/freshness_tinyml_uno/freshness_tinyml_model.h'


def c_float(value):
    return f'{float(value):.9g}f'


def write_header(nodes, gains, offsets, no_fruit_threshold):
    if len(nodes) > 255:
        raise ValueError('Tree exceeds uint8 node indexes')
    lines = [
        '#pragma once',
        '#include <Arduino.h>',
        '#include <avr/pgmspace.h>',
        '',
        '// Generated by export_arduino_model.py; banana freshness only.',
        '// Nine engineered inputs; int16 thresholds use per-feature Q factors.',
        '// 0=spoiled, 1=fresh, 2=no fruit.',
        f'constexpr uint8_t FRESHNESS_INPUTS = {len(FEATURES)};',
        f'constexpr uint8_t FRESHNESS_NODE_COUNT = {len(nodes)};',
        f'constexpr int16_t kNoFruitRawMq3ThresholdQ8 = {int(np.rint(no_fruit_threshold * GATE_Q))};',
        'const float kCustomToOpenGain[3] PROGMEM = {',
        '  ' + ', '.join(c_float(gains[sensor]) for sensor in ('MQ3', 'MQ5', 'MQ135')),
        '};',
        'const float kCustomToOpenOffset[3] PROGMEM = {',
        '  ' + ', '.join(c_float(offsets[sensor]) for sensor in ('MQ3', 'MQ5', 'MQ135')),
        '};',
        'const uint16_t kFeatureQ[FRESHNESS_INPUTS] PROGMEM = {',
        '  ' + ', '.join(str(value) for value in FEATURE_Q),
        '};',
        '',
        'struct __attribute__((packed)) FreshnessNode {',
        '  int16_t thresholdQ;',
        '  uint8_t right;',
        '  uint8_t feature; // 0..8 from FEATURES, 255=leaf',
        '  uint8_t fresh;   // leaf class only',
        '};',
        'static_assert(sizeof(FreshnessNode) == 5, "Unexpected tree node size");',
        'const FreshnessNode kFreshnessTree[FRESHNESS_NODE_COUNT] PROGMEM = {',
    ]
    for threshold, right, feature, fresh in nodes:
        lines.append(f'  {{{threshold}, {right}, {feature}, {fresh}}},')
    lines.extend(['};', ''])
    return '\n'.join(lines)


def blocked_validation(values, labels):
    # Fifteen observed seconds per group, never crossing class/session edges.
    groups = open_block_groups(values, labels)
    rows = []
    splitter = GroupShuffleSplit(n_splits=5, test_size=0.2, random_state=42)
    features = make_features(values)
    for train_index, test_index in splitter.split(values, labels, groups):
        model = make_model().fit(features.iloc[train_index], labels[train_index])
        quantized = quantize_model(model)
        predictions = predict_quantized(quantized, values.iloc[test_index])
        truth = labels[test_index]
        rows.append((
            balanced_accuracy_score(truth, predictions),
            f1_score(truth, predictions, average='macro'),
            recall_score(truth, predictions, pos_label=0),
        ))
    metrics = np.asarray(rows)
    print(f'blocked quantized balanced accuracy: {metrics[:, 0].mean():.4f} '
          f'(worst split {metrics[:, 0].min():.4f})')
    print(f'blocked quantized macro F1: {metrics[:, 1].mean():.4f}')
    print(f'blocked quantized spoiled recall: {metrics[:, 2].mean():.4f}')


def main():
    values, labels, open_fresh = open_training_data()
    open_rotten = load_open_resampled('banana_rotten.csv')
    custom_fresh = load_recording('banana_fresh_custom.csv', custom=True)
    custom_rotten = load_recording('banana_rotten_custom.csv', custom=True)
    no_fruit = load_recording('no_fruit.csv', custom=True)
    gains, offsets, gate, fresh_end, rotten_end, no_fruit_end = calibration(
        open_fresh, open_rotten, custom_fresh, custom_rotten, no_fruit
    )
    blocked_validation(values, labels)

    features = make_features(values)
    model = make_model().fit(features, labels)
    nodes = quantize_model(model)
    full_predictions = predict_quantized(nodes, values)
    print(f'open-data float/integer prediction agreement: '
          f'{np.mean(model.predict(features) == full_predictions):.4f}')
    for name, frame, expected in [
        ('held-out custom fresh', custom_fresh.iloc[fresh_end:], 1),
        ('held-out custom spoiled', custom_rotten.iloc[rotten_end:], 0),
        ('held-out no fruit', no_fruit.iloc[no_fruit_end:], 2),
    ]:
        raw = even_sample(frame, 3000)
        mapped = map_custom(raw, gains, offsets)
        predictions = predict_quantized(nodes, mapped, no_fruit_threshold=gate,
                                        raw_values=raw)
        if expected is None:
            print(f'{name}: {np.mean(predictions == 1):.3%} predicted fresh')
        else:
            print(f'{name}: {np.mean(predictions == expected):.3%} accuracy')

    OUTPUT.write_text(write_header(nodes, gains, offsets, gate))
    print(f'exported {len(nodes)} nodes, {model_flash_bytes(nodes)} tree bytes in PROGMEM')
    print(f'header: {OUTPUT}')


if __name__ == '__main__':
    main()
