"""Train and export the quantized nine-feature LIF freshness model for Uno."""

from pathlib import Path

import numpy as np
from sklearn.metrics import balanced_accuracy_score, f1_score, recall_score
from sklearn.model_selection import GroupShuffleSplit

from freshness_snn_model import fit_snn, model_flash_bytes, predict_snn
from freshness_tree_model import (
    FEATURES, GATE_Q, calibration, even_sample, load_open_resampled,
    load_recording, make_features, map_custom, open_block_groups,
    open_training_data,
)

OUTPUT = (Path(__file__).resolve().parent / 'arduino_sketches' /
          'freshness_snn_uno' / 'freshness_snn_model.h')


def c_float(value):
    return f'{float(value):.9g}f'


def write_header(model, gains, offsets, no_fruit_threshold):
    lines = [
        '#pragma once',
        '#include <Arduino.h>',
        '#include <avr/pgmspace.h>',
        '',
        '// Generated by export_arduino_snn.py; nine engineered inputs.',
        '// One fixed rate-coded LIF neuron per input and a quantized readout.',
        '// 0=spoiled, 1=fresh, 2=no fruit.',
        f'constexpr uint8_t SNN_INPUTS = {len(FEATURES)};',
        f'constexpr uint8_t SNN_NEURONS = {model.neurons};',
        'constexpr uint8_t SNN_STEPS = 8;',
        f'constexpr int16_t kNoFruitRawMq3ThresholdQ8 = {int(np.rint(no_fruit_threshold * GATE_Q))};',
        f'constexpr int32_t kSnnOutputBiasQ = {model.output_bias};',
        'const float kCustomToOpenGain[3] PROGMEM = {',
        '  ' + ', '.join(c_float(gains[s]) for s in ('MQ3', 'MQ5', 'MQ135')),
        '};',
        'const float kCustomToOpenOffset[3] PROGMEM = {',
        '  ' + ', '.join(c_float(offsets[s]) for s in ('MQ3', 'MQ5', 'MQ135')),
        '};',
        'const float kSnnCenter[SNN_INPUTS] PROGMEM = {',
        '  ' + ', '.join(c_float(v) for v in model.center),
        '};',
        'const float kSnnInvScale[SNN_INPUTS] PROGMEM = {',
        '  ' + ', '.join(c_float(v) for v in model.inv_scale),
        '};',
        'const int16_t kSnnReadout[SNN_NEURONS] PROGMEM = {',
        '  ' + ', '.join(str(int(v)) for v in model.readout),
        '};',
        '',
    ]
    return '\n'.join(lines)


def blocked_validation(values, labels):
    groups = open_block_groups(values, labels)
    features = make_features(values)
    rows = []
    for train, test in GroupShuffleSplit(
            n_splits=5, test_size=.2, random_state=42).split(values, labels, groups):
        model = fit_snn(features.iloc[train], labels[train])
        predicted = predict_snn(model, values.iloc[test])
        rows.append((
            balanced_accuracy_score(labels[test], predicted),
            f1_score(labels[test], predicted, average='macro'),
            recall_score(labels[test], predicted, pos_label=0),
        ))
    metrics = np.asarray(rows)
    print(f'blocked quantized balanced accuracy: {metrics[:, 0].mean():.4f} '
          f'(worst split {metrics[:, 0].min():.4f})')
    print(f'blocked quantized macro F1: {metrics[:, 1].mean():.4f}')
    print(f'blocked quantized spoiled recall: {metrics[:, 2].mean():.4f}')


def main():
    values, labels, open_fresh = open_training_data()
    open_rotten = load_open_resampled('banana_rotten.csv')
    custom_fresh = load_recording('banana_fresh_custom.csv', custom=True)
    custom_rotten = load_recording('banana_rotten_custom.csv', custom=True)
    custom_spoil = load_recording('banana_starts_to_spoil_custom.csv', custom=True)
    no_fruit = load_recording('no_fruit.csv', custom=True)
    gains, offsets, gate, fresh_end, rotten_end, no_fruit_end = calibration(
        open_fresh, open_rotten, custom_fresh, custom_rotten, no_fruit
    )
    blocked_validation(values, labels)
    model = fit_snn(make_features(values), labels)
    print(f'final model: {model.neurons} LIF neurons, {model_flash_bytes(model)} model bytes')
    print(f'all nine feature neurons have nonzero readout weights: '
          f'{np.all(model.readout != 0)}')
    for name, frame, expected in [
        ('held-out custom fresh', custom_fresh.iloc[fresh_end:], 1),
        ('held-out custom spoiled', custom_rotten.iloc[rotten_end:], 0),
        ('custom starts to spoil (diagnostic)', custom_spoil, None),
        ('held-out no fruit', no_fruit.iloc[no_fruit_end:], 2),
    ]:
        raw = even_sample(frame, 3000)
        mapped = map_custom(raw, gains, offsets)
        predicted = predict_snn(model, mapped, no_fruit_threshold=gate,
                                raw_values=raw)
        if expected is None:
            print(f'{name}: {np.mean(predicted == 1):.3%} predicted fresh')
        else:
            print(f'{name}: {np.mean(predicted == expected):.3%} accuracy')
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(write_header(model, gains, offsets, gate))
    print(f'header: {OUTPUT}')


if __name__ == '__main__':
    main()
