#pragma once
#include <Arduino.h>
#include <avr/pgmspace.h>

// Generated by export_arduino_snn.py; nine engineered inputs.
// One fixed rate-coded LIF neuron per input and a quantized readout.
// 0=spoiled, 1=fresh, 2=no fruit.
constexpr uint8_t SNN_INPUTS = 9;
constexpr uint8_t SNN_NEURONS = 9;
constexpr uint8_t SNN_STEPS = 8;
constexpr int16_t kNoFruitRawMq3ThresholdQ8 = 547;
constexpr int32_t kSnnOutputBiasQ = 5237;
const float kCustomToOpenGain[3] PROGMEM = {
  0.247288803f, -0.710491368f, 10.2661597f
};
const float kCustomToOpenOffset[3] PROGMEM = {
  82.9912965f, 1141.0757f, -665.098859f
};
const float kSnnCenter[SNN_INPUTS] PROGMEM = {
  2.51493979f, 0.255735904f, -582.645996f, 105.45771f, 10.5773945f, 371.179779f, 688.103699f, 895.463867f, 209.137787f
};
const float kSnnInvScale[SNN_INPUTS] PROGMEM = {
  1.28633726f, 19.2673149f, 0.00599292712f, 0.0244451389f, 0.202345625f, 0.0101920497f, 0.00569751672f, 0.00318494299f, 0.0116506107f
};
const int16_t kSnnReadout[SNN_NEURONS] PROGMEM = {
  284, -565, 2436, -2234, 1826, -1486, -1498, -1580, -2721
};
